---
output:
  md_document:
    variant: markdown_github
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```
# docaids

R code is often first generated in a haphazard and exploratory way, particularly 
in a research environment.  This 
package helps to automatically discover and/or document the structure of local 
variables in functions.  This makes it easier to both understand old existing 
code or code you've been given, and document it in roxygen.  It currently provides 4 main services, 
though all 4 of them are interrelated.

- Functions inserted into other functions you want to document
    - `doc_vars_in_this_func` is the function that does most of the work.  It finds all of the variables defined inside the function where it is called and then runs the R  function "str" on each of them to show the structure of each variable.
    - `doc_vars_in_this_func_once` is a wrapper function that can be used in place of `doc_vars_in_this_func` when you want to make sure that `doc_vars_in_this_func` is only called one time for any given function, no matter how many times that function is called in a program.  The intent here is to avoid lots of duplicate output because you generally only need one copy of the structures.
    - `bump_global_ctr_for_cur_func` is a support function for `doc_vars_in_this_func_once`, though it can be used on its own if you want to count the number of times a function is called during a run of a program.  It simply creates a unique global counter for the function at run time if it doesn't already exist and then increments that counter each time the function is called.
- Function run on output from functions above
    - `generate_func_var_roxygen_comments` is a function that reads the output generated by `doc_vars_in_this_func` and formats the information to write it back out in a form that can be pasted into the roxygen documentation at the start of a function.
    
There must be much more sophisticated ways to do what I've done, but this does seem to work...


## Installation  
You can install docaids from github with:  
```R
# install.packages ("devtools")  
devtools::install_github ("langfob/docaids")
```

## Example  
This is a basic example which shows you how to solve a common problem:  
- (An example that shows how to use the package to solve a simple problem.)
```R
...
```

## Overview  
- (An overview that describes the main components of the package. For more complex packages, this will point to vignettes for more details.)   

